name: habibbintofajjal
description: This is a business card app for Habib Bin Tofajjal

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: LobsterTwo-Bold
      fonts:
        - asset: fonts/LobsterTwo-Bold.ttf

    - family: Viga-Regular
      fonts:
        - asset: fonts/Viga-Regular.ttf
